Italiano/Italiano/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('restaurant.urls')),
]

if settings.DEBUG:
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Italiano/restaurant/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index),
    path('book/', views.book),
    path('menu/', views.menu),
    path('gallery/', views.gallery),
    path('booking/', views.reservation),
    path('contact/', views.contact),
    path('contact_result/', views.contact_result),
]

Italiano/restaurant/models.py
from django.db import models
from django.conf import settings
from django.core.validators import RegexValidator

class Category(models.Model):
    name = models.CharField(max_length=50)

    class Meta():
        ordering = ['name']
        verbose_name = 'category'
        verbose_name_plural = "categories"

    def __str__(self):
        return self.name

class Dish(models.Model):
    name = models.CharField(max_length=50)
    category = models.ForeignKey(
        Category,
        on_delete=models.CASCADE,
        null=True
    )
    description = models.CharField(max_length=150)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    recomended = models.BooleanField()
    img = models.ImageField(verbose_name='image')

    class Meta():
        ordering = ['name']
        verbose_name = 'dish'
        verbose_name_plural = "dishes"

    def __str__(self):
        return self.name
    
class Reservation(models.Model):
    name = models.CharField(max_length=50)
    email = models.EmailField()
    number = models.CharField(
        max_length=13,
        validators=[RegexValidator(r'^\+\d{12}$')]
    )
    person_count = models.IntegerField()
    date = models.DateField()
    time = models.TimeField()
    special_request = models.TextField(null=True)

    def __str__(self):
        return f'{self.name}-{self.date}'

class Contact(models.Model):
    name = models.CharField(max_length=50)
    email = models.EmailField()    
    message = models.TextField(null=True)

    def __str__(self):
        return f'{self.name}-{self.email}'

Italiano/restaurant/views.py
from django.shortcuts import render, get_list_or_404, get_object_or_404

from datetime import datetime

from . import models

def index(request):
    return render(request, 'index.html')

def menu(request):
    recomended_dishes = get_list_or_404(models.Dish, recomended=True)
    categories = get_list_or_404(models.Category)

    return render(request, 'menu.html', {
        'recomended_dishes': recomended_dishes,
        'categories': categories,
    })

def gallery(request):
    return render(request, 'gallery.html')

def reservation(request):
    return render(request, 'booking.html')

def book(request):
    if 'name' in request.GET:

        reservation = models.Reservation(
            name=request.GET['name'],
            email=request.GET['email'],
            number=request.GET['number'],
            person_count=request.GET['people'],
            date=datetime.strptime(request.GET['date'], "%d/%m/%Y").date(),
            time=request.GET['time'],
            special_request=request.GET['request'],
        )
        reservation.save()
        message = 'You succesfuly booked your table!'
    else:
        message = 'Something went wrong. Try again'
    return render(request, 'booking_result.html', {'message': message})

def contact(request):
    return render(request, 'contact.html')

def contact_result(request):
    if 'username' in request.GET:
        contact = models.Contact(
            name=request.GET['username'],
            email=request.GET['useremail'],
            message=request.GET['message'],
        )
        contact.save()
        message = 'You succesfuly send us message!'
    else:
        message = 'Something went wrong. Try again'
    return render(request, 'contact_result.html', {'message': message})

Italiano/restaurant/templates/base.html
<!DOCTYPE html>
<html>

{% include "head.html" %}

<body>

    <div class="page-holder">
        {% include "header.html" %}

        {% block content %}
        {% endblock content %}

        {% include "footer.html" %}
        <div id="scrollTop" class="btn-unique"><i class="fa fa-angle-up"></i></div>

    </div>

    {% include "scripts.html" %}

</body>

</html>

Italiano/restaurant/templates/booking.html
{% extends 'base.html' %}

{% block content %}

<section id="booking" class="booking">
    <div class="container text-center">
        <header>
            <h2>Order your table</h2>
            <h3>Enjoy your meal at our restaurant</h3>
        </header>

        <div class="row">
            <div class="form-holder col-md-10 col-md-push-1 text-center">
                <div class="ribbon">
                    <i class="fa fa-star"></i>
                </div>

                <h2>Make a reservation</h2>
                <h3>Book your table now</h3>

                <form id="booking-form" method="get" action="/book/">
                    <div class="row">
                        <div class="col-md-10 col-md-push-1">
                            <div class="row">
                                <label for="name" class="col-sm-6 unique">Name
                                    <input name="name" type="text" id="name" required>
                                </label>
                                <label for="email" class="col-sm-6 unique">Email
                                    <input name="email" type="email" id="email" required>
                                </label>
                                <label for="number" class="col-sm-6 unique">Number
                                    <input name="number" type="text" id="number" required>
                                </label>
                                <label for="people" class="col-sm-6 unique">How Many People
                                    <input name="people" type="number" id="people" min="1" required>
                                </label>
                                <label for="date" class="col-sm-6 unique">Date
                                    <input name="date" type="text" id="date" class="datepicker-here" data-language='en' required>
                                </label>
                                <label for="time" class="col-sm-6 unique">Time
                                    <input name="time" type="text" id="time" class="timepicker" required>
                                </label>
                                <label for="request" class="col-sm-12 unique">Special Request
                                    <textarea id="request" name="request"></textarea>
                                </label>
                                <div class="col-sm-12">
                                    <button type="submit" class="btn-unique">Book Now</button>
                                </div>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</section>

{% endblock %}

Italiano/restaurant/templates/booking_form.html
{% block content %}

<form id="booking-form" method="get" action="/book/">
    <div class="row">
        <div class="col-md-10 col-md-push-1">
            <div class="row">
                <label for="name" class="col-sm-6 unique">Name
                    <input name="name" type="text" id="name" required>
                </label>
                <label for="email" class="col-sm-6 unique">Email
                    <input name="email" type="email" id="email" required>
                </label>
                <label for="number" class="col-sm-6 unique">Number
                    <input name="number" type="text" id="number" required>
                </label>
                <label for="people" class="col-sm-6 unique">How Many People
                    <input name="people" type="number" id="people" min="1" required>
                </label>
                <label for="date" class="col-sm-6 unique">Date
                    <input name="date" type="text" id="date" class="datepicker-here" data-language='en' required>
                </label>
                <label for="time" class="col-sm-6 unique">Time
                    <input name="time" type="text" id="time" class="timepicker" required>
                </label>
                <label for="request" class="col-sm-12 unique">Special Request
                    <textarea id="request" name="request"></textarea>
                </label>
                <div class="col-sm-12">
                    <button type="submit" class="btn-unique">Book Now</button>
                </div>
            </div>
        </div>
    </div>
</form>
{% endblock %}

Italiano/restaurant/templates/booking_result.html
{% extends 'base.html' %}

{% block content %}

<section id="booking" class="booking">
    <div class="container text-center">
        <header>
            <h2>Order your table</h2>
            <h3>Enjoy your meal at our restaurant</h3>
        </header>

        <div class="row">
            <div class="form-holder col-md-10 col-md-push-1 text-center">
                <div class="ribbon">
                    <i class="fa fa-star"></i>
                </div>

                <h2>Make a reservation</h2>
                <h3>Book your table now</h3>

                <br>
                <h4>{{message}}</h4>
                <br>

            </div>
        </div>
    </div>
</section>

{% endblock %}

Italiano/restaurant/templates/contact.html
{% extends 'base.html' %}

{% block content %}

<section id="contact" class="contact">
    <div id="map"></div>
    <div class="container text-center">
        <div class="form-holder">
            <header>
                <h2>Contact Us</h2>
                <h3>Feel free to contact us</h3>
            </header>

            <form method="get" action="/contact_result/" id="contact-form">
                <div class="row">
                    <label for="user-name" class="col-sm-6 unique">Name
                        <input type="text" name="username" id="user-name" required>
                    </label>
                    <label for="user-email" class="col-sm-6 unique">Email
                        <input type="email" name="useremail" id="user-email" required>
                    </label>
                    <label for="message" class="col-sm-12 unique">Your Message
                        <textarea name="message" id="message" required></textarea>
                    </label>
                    <div class="col-sm-12">
                        <button type="submit" class="btn-unique" id="submit">Send</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</section>

{% endblock %}

Italiano/restaurant/templates/contact_result.html
{% extends 'base.html' %}

{% block content %}

<section id="contact" class="contact">
    <div id="map"></div>
    <div class="container text-center">
        <div class="form-holder">
            <header>
                <h2>Contact Us</h2>
                <h3>Feel free to contact us</h3>
            </header>

            <br>
            <h4>{{ message }}</h4>
            <br>
        </div>
    </div>
</section>

{% endblock %}

Italiano/restaurant/templates/event.html
{% extends 'base.html' %}

{% block content %}

<section id="events" class="events">
    <div class="container">
        <header class="text-center">
            <h2>Upcoming Events</h2>
            <h3>Don’t miss our awesome events</h3>
        </header>

        <div class="row">
            <!-- Profile Side  -->
            <div class="col-sm-6">
                <div class="profile has-border" style="background-image: url(img/event-bg.jpg);">
                    <ul class="date list-unstyled list-inline clearfix">
                        <li class="day pull-left">15<sup>th</sup></li>
                        <li class="month pull-left">December <span>2016</span></li>
                    </ul>
                </div>
            </div>

            <!-- Details Side  -->
            <div class="col-sm-6">
                <div class="details">
                    <h3>Italian Master Class</h3>
                    <h4 class="text-primary">15 December 2016 | 20:00</h4>
                    <p class="lead">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat..</p>
                    <a href="#" class="read-more btn-unique">Read More</a>
                </div>
            </div>
        </div>
    </div>
</section>

{% endblock %}

Italiano/restaurant/templates/footer.html
{%load static%}

<footer id="mainFooter" class="mainFooter">
    <div class="container">
        <div class="row">
            <div class="col-md-4 brief">
                <div class="header">
                    <img src="{% static 'img/logo-footer.png' %}" alt="italiano" width="100">
                </div>
                <p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.</p>
            </div>

            <div class="col-md-4 contact">
                <div class="header">
                    <h6>Contact</h6>
                </div>
                <ul class="contact list-unstyled">
                    <li><span class="icon-map text-primary"></span>Basioun, 23 July st, Egypt</li>
                    <li><a href="mailto:Italiano@Company.com"><span class="icon-phone text-primary"></span>Italiano@Company.com</a></li>
                    <li><span class="icon-mail text-primary"></span>9465 7675 294</li>
                    <li><span class="icon-printer text-primary"></span>333-999-666</li>
                </ul>
            </div>

            <div class="col-md-4 newsletter">
                <div class="header">
                    <h6>Newsletter</h6>
                </div>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit sed do eiusmo.</p>
                <form action="#" id="subscribe" class="clearfix">
                    <input type="email" name="subscribtion-email" placeholder="Enter Your Email Address" class="pull-left">
                    <button type="submit" class="btn-unique has-border pull-left">Subscribe</button>
                </form>
            </div>
        </div>

        <ul class="social list-unstyled list-inline">
            <li><a href="#" target="_blank" title="Facebook"><i class="fa fa-facebook"></i></a></li>
            <li><a href="#" target="_blank" title="Twitter"><i class="fa fa-twitter"></i></a></li>
            <li><a href="#" target="_blank" title="Instagram"><i class="fa fa-instagram"></i></a></li>
            <li><a href="#" target="_blank" title="Google plus"><i class="fa fa-google-plus"></i></a></li>
            <li><a href="#" target="_blank" title="Pinterest"><i class="fa fa-pinterest"></i></a></li>
            <li><a href="#" target="_blank" title="Skype"><i class="fa fa-skype"></i></a></li>
        </ul>
    </div>

    <div class="copyrights">
        <div class="container">
            <div class="row">
                <div class="col-sm-5">
                    <ul class="list-unstyled list-inline">
                        <li><a href="#">Policy Privacy</a></li>
                        <li><a href="#">Terms of Use</a></li>
                        <li><a href="#">Contact</a></li>
                    </ul>
                </div>

                <div class="col-sm-7">
                    <p>&copy; 2017 Italiano Restaurant. Template By <a href="https://bootstraptemple.com/" target="_blank">BootstrapTemple.com</a></p>
                    <!-- Please do not remove the backlink to us unless you have purchased the attribution-free license at https://bootstraptemple.com. It is part of the license conditions. Thanks for understanding :) -->
                </div>
            </div>
        </div>
    </div>
</footer>

Italiano/restaurant/templates/head.html
{% load static%}

<head>
    <meta charset="utf-8">
    <!-- Responsive meta -->
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- IE Compatibility meta -->
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <!-- Description meta -->
    <meta name="description" content="...">
    <!-- Author meta -->
    <meta name="author" content="Bootstrap Temple">

    <!-- Page Title -->
    <title>Italiano Restaurant</title>
    <!-- Favicon -->
    <link rel="shortcut icon" href="{% static 'img/favicon.ico' %}">

    <!-- Bootstrap -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <!-- Custom font icons -->
    <link rel="stylesheet" href="https://file.myfontastic.com/6AeAYiqp5KBjSiZ2tE8WJW/icons.css">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <!-- Slider -->
    <link rel="stylesheet" href="{% static 'css/slider.min.css' %}">
    <!-- Lightbox Pop up -->
    <link rel="stylesheet" href="{% static 'css/lightbox.min.css' %}">
    <!-- Datepicker -->
    <link rel="stylesheet" href="{% static 'css/datepicker.min.css' %}">
    <!-- Datepicker -->
    <link rel="stylesheet" href="{% static 'css/timepicki.min.css' %}">
    <!-- Owl Carousel -->
    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
    <!-- Custom CSS -->
    <link rel="stylesheet" href="{% static 'css/style.default.css' %}">
    <!-- Modernizr -->
    <script type="text/javascript" src="{% static 'js/modernizr.custom.79639.min.js' %}"></script>
</head>

Italiano/restaurant/templates/header.html
{% load static %}
<header class="header">
    <nav class="navbar navbar-default navbar-fixed-top">
        <div class="container">
            <div class="navbar-header"><a href="/" class="navbar-brand"><img src="{% static 'img/logo.png' %}" alt="Italiano" width="100"></a>
                <div class="navbar-buttons">
                    <button type="button" data-toggle="collapse" data-target=".navbar-collapse" class="navbar-toggle navbar-btn">Menu<i class="fa fa-align-justify"></i></button>
                </div>
            </div>
            <div id="navigation" class="collapse navbar-collapse navbar-right">
                <ul class="nav navbar-nav">
                    <li class="active"><a href="/">Home</a></li>
                    <li><a href="/menu">Menu</a></li>
                    <li><a href="/gallery">Gallery</a></li>
                    <li><a href="/booking">Reservation</a></li>
                    <li><a href="/contact">Contact</a></li>
                </ul>
            </div>
        </div>
    </nav>
</header>

Italiano/restaurant/templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<section id="hero" class="hero">
    <div id="slider" class="sl-slider-wrapper">

        <div class="sl-slider">
            <!-- slide -->
            <div class="sl-slide bg-1" data-orientation="horizontal" data-slice1-rotation="-25" data-slice2-rotation="-25" data-slice1-scale="2" data-slice2-scale="2">
                <div class="sl-slide-inner" style="background-image: url({% static 'img/hero-bg.jpg'%});">
                    <div class="container">
                        <h2>This is <span class="text-primary">Italiano restaurant</span></h2>
                        <h1>Bootstrap Template</h1>
                        <p>An elegant Bootstrap template brought to you by <a href="https://bootstraptemple.com/" target="_blank">Bootstrap Temple</a>.</p>
                    </div>
                </div>
            </div>
            <!-- slide -->
            <div class="sl-slide bg-2" data-orientation="vertical" data-slice1-rotation="10" data-slice2-rotation="-15" data-slice1-scale="1.5" data-slice2-scale="1.5">
                <div class="sl-slide-inner" style="background-image: url({% static 'img/hero-bg02.jpg' %});">
                    <div class="container">
                        <h1>lorem ipsum dolor sit amit</h1>
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt.</p>
                    </div>
                </div>
            </div>
            <!-- slide -->
            <div class="sl-slide bg-3" data-orientation="horizontal" data-slice1-rotation="3" data-slice2-rotation="3" data-slice1-scale="2" data-slice2-scale="1">
                <div class="sl-slide-inner" style="background-image: url({% static 'img/hero-bg03.jpg' %});">
                    <div class="container">
                        <h2>Visit <span class="text-primary">italiano restaurant</span></h2>
                        <h1>lorem ipsum dolor sit amit</h1>
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt.</p>
                    </div>
                </div>
            </div>
        </div><!-- End sl-slider -->

        <!-- slider pagination -->
        <nav id="nav-dots" class="nav-dots">
            <span class="nav-dot-current"></span>
            <span></span>
            <span></span>
        </nav>

        <!-- scroll down btn -->
        <a id="scroll-down" href="#about" class="hidden-xs"></a>

        <!-- social icons menu -->
        <div class="social">
            <div class="wrapper">
                <ul class="list-unstyled">
                    <li><a href="#" title="facebook" target="_blank"><i class="fa fa-facebook"></i></a></li>
                    <li><a href="#" title="twitter" target="_blank"><i class="fa fa-twitter"></i></a></li>
                    <li><a href="#" title="pinterest" target="_blank"><i class="fa fa-pinterest"></i></a></li>
                    <li><a href="#" title="instagram" target="_blank"><i class="fa fa-instagram"></i></a></li>
                </ul>
                <span>Follow us on</span>
            </div>
        </div>
    </div><!-- End slider-wrapper -->
</section>


<!-- Details -->
<section id="details" class="details">
    <div class="container">
        <div class="row">
            <div class="col-sm-6">
                <div class="heading text-center">
                    <p>Call Us Now For</p>
                    <h5>Home Delivery</h5>
                </div>
                <a href="tel:9870988764" class="phone">987 098 8764</a>
            </div>

            <div class="col-sm-6">
                <div class="heading text-center">
                    <p>Check Our Clients'</p>
                    <h5>Rating &amp; Reviews</h5>
                </div>
                <a href="#" class="reviews btn-unique"><i class="fa fa-angle-right"></i></a>
            </div>
        </div>
    </div>
</section>
<!-- End Details-->


<!-- About Section -->
<section id="about" class="about">
    <div class="container text-center">
        <header>
            <h2>About Restaurant</h2>
            <h3>Check our story</h3>
        </header>
        <p class="lead">Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur</p>
    </div>
</section>


<section id="services" class="services">
    <div class="container text-center">
        <header>
            <h2>We provide the following</h2>
            <h3>Our Specialities</h3>
        </header>

        <div class="row">
            <!-- item -->
            <div class="col-sm-4 service">
                <div class="icon">
                    <i class="icon-like"></i>
                </div>
                <div class="text">
                    <h4>Clean Environment</h4>
                    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,</p>
                </div>
            </div>

            <!-- item -->
            <div class="col-sm-4 service">
                <div class="icon">
                    <i class="icon-hat"></i>
                </div>
                <div class="text">
                    <h4>Lovely &amp; expert chefs</h4>
                    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,</p>
                </div>
            </div>

            <!-- item -->
            <div class="col-sm-4 service">
                <div class="icon">
                    <i class="icon-plate"></i>
                </div>
                <div class="text">
                    <h4>Fresh and tasty food</h4>
                    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,</p>
                </div>
            </div>
        </div>
    </div>
</section>

{% endblock %}

Italiano/restaurant/templates/menu.html
{% extends 'base.html' %}

{% block content %}

<section id="dishes" class="dishes">
    <div class="container text-center">
        <header>
            <h2>Recomended Dishes</h2>
            <h3>Checkout our recomendations</h3>
        </header>
        <!-- Set up your HTML -->
        <div class="owl-carousel owl-theme">
            <!-- item -->
            {% for dish in recomended_dishes %}
                <div class="dish">
                    <div class="profile">
                        <img src="{{ dish.img.url }}" class="img-responsive" alt="dish name">
                        <div class="price">
                            <span>{{ dish.price }}</span>
                        </div>
                    </div>
                    <div class="text">
                        <h4>{{dish.name}}</h4>
                        <p>{{dish.description}}</p>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
</section>

<section id="menu" class="menu">
    <div class="container">
        <header class="text-center">
            <h2>Our food menu</h2>
            <h3>Our most popular menu</h3>
        </header>

        <div class="menu">
            <!-- Tabs Navigatin -->
            <ul class="nav nav-tabs text-center has-border" role="tablist">
                <li role="presentation"><a href="#salads" aria-controls="salads" role="tab" data-toggle="tab">Salads</a></li>
                <li role="presentation"><a href="#mains" aria-controls="mains" role="tab" data-toggle="tab">Mains</a></li>
                <li role="presentation"><a href="#pizza" aria-controls="pizza" role="tab" data-toggle="tab">Pizza</a></li>
                <li role="presentation"><a href="#deserts" aria-controls="deserts" role="tab" data-toggle="tab">Deserts</a></li>
                <li role="presentation"><a href="#drinks" aria-controls="drinks" role="tab" data-toggle="tab">Drinks</a></li>
            </ul>

            <!-- Tab panes -->
            <div class="tab-content">
                {% for category in categories %}                
                    <div role="tabpanel" class="tab-pane fade" id="{{category.name}}">
                        <div class="row">
                            {% for dish in category.dish_set.all %}
                                <!-- {% if dish.category.name == category.name %} -->
                                    <div class="col-sm-6">
                                        {% if dish.recomended %}
                                            <div class="menu-item recommended has-border clearfix">
                                                <div class="item-details pull-left">
                                                    <h5>{{dish.name}}</h5>
                                                    <p>{{dish.description}}</p>
                                                </div>
                                                <div class="item-price pull-right">
                                                    <strong class="text-large text-primary">{{dish.price}}</strong>
                                                    <span class="text-medium">Recommended</span>
                                                </div>
                                            </div>
                                        {% else %}
                                            <div class="menu-item clearfix">
                                                <div class="item-details pull-left">
                                                    <h5>{{dish.name}}</h5>
                                                    <p>{{dish.description}}</p>
                                                </div>
                                                <div class="item-price pull-right">
                                                    <strong class="text-large text-primary">{{dish.price}}</strong>
                                                </div>
                                            </div>
                                        {% endif %}
                                    </div>
                                <!-- {% endif %} -->
                            {% endfor %}
                                        
                        </div>
                    </div>                   
                {% endfor %}
            </div>
        </div>
    </div>
</section>

{% endblock %}

Italiano/restaurant/templates/scripts.html
{% load static%}

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/jquery.ba-cond.min.js' %}"></script>
<script src="{% static 'js/jquery.slitslider.min.js' %}"></script>
<script src="{% static 'js/owl.carousel.min.js' %}"></script>
<script src="{% static 'js/lightbox.min.js' %}"></script>
<script src="{% static 'js/datepicker.min.js' %}"></script>
<script src="{% static 'js/datepicker.en.min.js' %}"></script>
<script src="{% static 'js/timepicki.min.js' %}"></script>
<script src="{% static 'js/jquery.validate.min.js' %}"></script>
<script src="{% static 'js/smooth.scroll.min.js' %}"></script>
<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyC0dSWcBx-VghzhzQB6oCMTgeXMOhCYTvk"></script>
<script src="{% static 'js/map.min.js' %}"></script>
<script src="{% static 'js/script.js' %}"></script>